services:
  datascience-notebook:
    container_name: my_datascience-notebook
    build:
      context: "./jupyterlab"
    ports:
      - "8888:8888"
    volumes:
      - ./jupyterlab/work:/home/jovyan/work
  redis:
    container_name: my_datascience-redis
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "6001:8001"
    volumes:
      - ./redis/data:/data
